# Generated by Django 5.2.7 on 2025-11-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_bookpage_avg_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='bookpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='bookpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='booksindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
        migrations.DeleteModel(
            name='BookPageTag',
        ),
        migrations.DeleteModel(
            name='BooksIndexPage',
        ),
    ]
