# Generated by Django 5.2.7 on 2025-11-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_bookpage_authors_remove_bookpage_cover_image_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This is automatically updated when a page is viewed.'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This is automatically updated when a page is viewed.'),
        ),
        migrations.AddField(
            model_name='idiompage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This is automatically updated when a page is viewed.'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This is automatically updated when a page is viewed.'),
        ),
        migrations.AlterField(
            model_name='dictionaryentrypage',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This is automatically updated when a page is viewed.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_item',
            field=models.ForeignKey(blank=True, help_text='Optional: Manually select a page to feature. If empty, a random Phrase of the Day will be chosen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
