# Generated by Django 5.2.7 on 2025-11-16 19:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpostpage_view_count_eventpage_view_count_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiompage',
            name='idiom_basic_defintion_gurmukhi',
            field=models.TextField(blank=True, help_text='Basic definition in Gurmukhi (note: typo from source JSON)'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='definition_gurmukhi',
            field=models.TextField(blank=True, help_text='Simple definition in Gurmukhi'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='enriched_definition_english',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed explanation in English'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='enriched_definition_gurmukhi',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed explanation in Gurmukhi'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='enriched_definition_shahmukhi',
            field=models.TextField(blank=True, help_text='Detailed explanation in Shahmukhi'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='example_sentences_gurmukhi',
            field=wagtail.fields.RichTextField(blank=True, help_text='Example sentences in Gurmukhi'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='grammar',
            field=models.CharField(blank=True, help_text='Type: phrase, idiom, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='phrase_id',
            field=models.PositiveIntegerField(blank=True, help_text='The original ID from the JSON file.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='sound',
            field=models.ForeignKey(blank=True, help_text='Audio pronunciation file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='source',
            field=models.CharField(blank=True, help_text='Source attribution', max_length=255),
        ),
        migrations.AddField(
            model_name='phrasepage',
            name='synonyms_gurmukhi',
            field=models.CharField(blank=True, max_length=500, verbose_name='Synonyms (Gurmukhi)'),
        ),
        migrations.AlterField(
            model_name='phrasepage',
            name='example_usage',
            field=wagtail.fields.RichTextField(blank=True, help_text='Example usage (legacy field)'),
        ),
        migrations.AlterField(
            model_name='phrasepage',
            name='explanation',
            field=wagtail.fields.RichTextField(blank=True, help_text='General explanation (legacy field)'),
        ),
        migrations.AlterField(
            model_name='phrasepage',
            name='meaning_english',
            field=models.CharField(max_length=500, verbose_name='Simple English meaning'),
        ),
        migrations.AlterField(
            model_name='phrasepage',
            name='roman_diacritics',
            field=models.CharField(blank=True, max_length=500, verbose_name='Roman (with diacritics)'),
        ),
        migrations.AlterField(
            model_name='phrasepage',
            name='roman_simple',
            field=models.CharField(max_length=500, verbose_name='Roman (simple)'),
        ),
        migrations.AlterField(
            model_name='phrasepage',
            name='source_reference',
            field=models.CharField(blank=True, help_text='Source reference (legacy field)', max_length=255),
        ),
        migrations.AlterField(
            model_name='phrasepage',
            name='synonyms',
            field=models.CharField(blank=True, help_text='Synonyms (legacy field)', max_length=500),
        ),
    ]
