# Generated by Django 5.2.7 on 2025-11-16 19:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_idiompage_idiom_basic_defintion_gurmukhi_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.CharField(default='temp_id', help_text='Original ID from JSON', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bluesky',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL to cover image', max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='mastodon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original URL from punjabisahit.com', max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL to profile image', max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='threads',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='tiktok',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='youtube',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='codeinjection_foot',
            field=models.TextField(blank=True, help_text='Code to inject before </body>'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='codeinjection_head',
            field=models.TextField(blank=True, help_text='Code to inject in <head>'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='comment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='custom_template',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Auto-generated excerpt'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='feature_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='feature_image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='feature_image_url',
            field=models.URLField(blank=True, help_text='URL to feature image', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='frontmatter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='html_content',
            field=models.TextField(blank=True, help_text='Raw HTML content from JSON'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='og_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original URL from punjabisahit.com', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='post_id',
            field=models.CharField(blank=True, help_text='Original ID from JSON', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Original publish date', null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='reading_time',
            field=models.IntegerField(default=0, help_text='Reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='twitter_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='twitter_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Last updated date', null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='uuid',
            field=models.UUIDField(blank=True, help_text='UUID from original post', null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('members', 'Members Only')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ForeignKey(blank=True, help_text='Local uploaded image (legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 1), ('image', 2), ('video', 3), ('code', 6), ('quote', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr']}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash/Shell')], 'label': 'Language', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('code', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': True, 'rows': 3}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('quote', 7), ('attribution', 8)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='intro',
            field=models.CharField(blank=True, help_text='Custom excerpt / intro', max_length=500),
        ),
    ]
