# Generated by Django 5.2.7 on 2025-11-17 02:58

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_author_author_id_author_bluesky_author_cover_image_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BooksIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='awards',
            field=wagtail.fields.RichTextField(blank=True, help_text='Awards and achievements'),
        ),
        migrations.AddField(
            model_name='author',
            name='biography_english',
            field=wagtail.fields.RichTextField(blank=True, help_text='Biography in English'),
        ),
        migrations.AddField(
            model_name='author',
            name='biography_gurmukhi',
            field=wagtail.fields.RichTextField(blank=True, help_text='Biography in Gurmukhi'),
        ),
        migrations.AddField(
            model_name='author',
            name='biography_hindi',
            field=wagtail.fields.RichTextField(blank=True, help_text='Biography in Hindi'),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birthplace',
            field=models.CharField(blank=True, help_text='Place of birth', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, help_text='Date of death (leave blank if living)', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this author on homepage'),
        ),
        migrations.AddField(
            model_name='author',
            name='literary_style',
            field=models.CharField(blank=True, help_text='Writing style or genres (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='name_english',
            field=models.CharField(blank=True, help_text='Author name in English', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='name_gurmukhi',
            field=models.CharField(blank=True, help_text='Author name in Gurmukhi', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='name_hindi',
            field=models.CharField(blank=True, help_text='Author name in Hindi', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='name_shahmukhi',
            field=models.CharField(blank=True, help_text='Author name in Shahmukhi', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='profile_photo',
            field=models.ForeignKey(blank=True, help_text='Profile photo (use this for new entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='author',
            name='wikipedia_link',
            field=models.URLField(blank=True, help_text='Wikipedia page'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Primary author of this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='home.author'),
        ),
        migrations.AddField(
            model_name='dictionaryentrypage',
            name='origin',
            field=models.CharField(blank=True, choices=[('punjabi', 'Punjabi'), ('arabic', 'Arabic'), ('persian', 'Persian'), ('sanskrit', 'Sanskrit'), ('urdu', 'Urdu'), ('hindi', 'Hindi'), ('english', 'English'), ('other', 'Other')], help_text='Language origin of the word', max_length=100),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for list views'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='speakers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Authors/speakers for this event', related_name='speaking_events', to='home.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Legacy bio field - use biography_english for new entries'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL to cover image (legacy)', max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, help_text='Current location', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Legacy name field - use name_english for new entries', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL to profile image (legacy)', max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='temp-slug', help_text='URL-friendly version of name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, help_text='Personal website', max_length=500),
        ),
        migrations.CreateModel(
            name='AuthorDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_pages', to='home.author')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, help_text='This is automatically updated when a page is viewed.')),
                ('title_gurmukhi', models.CharField(max_length=500)),
                ('title_english', models.CharField(blank=True, max_length=500)),
                ('title_hindi', models.CharField(blank=True, max_length=500)),
                ('title_shahmukhi', models.CharField(blank=True, max_length=500)),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Number of pages', null=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('printer', models.CharField(blank=True, help_text='Printing company', max_length=255)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN number', max_length=20)),
                ('edition', models.CharField(blank=True, help_text='Edition (e.g., First Edition, Revised)', max_length=100)),
                ('description_gurmukhi', wagtail.fields.RichTextField(blank=True, help_text='Book description in Gurmukhi')),
                ('description_english', wagtail.fields.RichTextField(blank=True, help_text='Book description in English')),
                ('description_hindi', wagtail.fields.RichTextField(blank=True, help_text='Book description in Hindi')),
                ('category', models.CharField(blank=True, help_text='Category: Literature, History, Religious, Poetry, etc.', max_length=100)),
                ('purchase_link', models.URLField(blank=True, help_text='Link to purchase the book')),
                ('pdf_link', models.URLField(blank=True, help_text='Link to PDF version if available')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='home.author')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BookPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.bookpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bookpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.BookPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
