# Generated by Django 5.2.7 on 2025-11-17 07:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_authorsindexpage_booksindexpage_alter_author_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('to_read', 'To Read'), ('reading', 'Currently Reading'), ('read', 'Read'), ('completed', 'Completed')], default='to_read', max_length=20)),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite')),
                ('current_page', models.PositiveIntegerField(default=0, help_text='Current page number')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the book')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating out of 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_reading', models.DateTimeField(blank=True, help_text='When user started reading', null=True)),
                ('finished_reading', models.DateTimeField(blank=True, help_text='When user finished reading', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='home.bookpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book Status',
                'verbose_name_plural': 'User Book Statuses',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
